name: GUI Release
on:
  push
jobs:
  Build-Action:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install npm dependencies
        run: npm ci
        working-directory: ./sw/wulpus-frontend
      - name: Build UI (react)
        run: python build.py
        working-directory: ./sw/wulpus-frontend
      - name: Install python dependencies
        working-directory: ./sw/wulpus
        run: pip install -r requirements.txt
      - name: Build .exe
        working-directory: ./sw/wulpus
        run: pyinstaller ./main.spec --noconfirm
      - name: Write version info to artifact
        working-directory: ./sw/wulpus
        shell: pwsh
        run: |
          $commitHash = (git rev-parse HEAD).Trim()
          $commitDateFull = (git show -s --format=%cd --date=iso-strict HEAD).Trim()
          $commitDate = $commitDateFull.Split('T')[0]
          $text = "$commitHash from $commitDate"
          $target = "./dist/main/_internal/wulpus/version.txt"
          New-Item -ItemType Directory -Force -Path (Split-Path -Parent $target) | Out-Null
          Set-Content -Path $target -Value $text -Encoding UTF8
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: wulpus-all-in-one
          path: ./sw/wulpus/dist/main/
          compression-level: 8